var a, c, canvas, context, d, dejong, e, flage, flagg, height, i, width, x, y;

x = 1;

y = 1;

a = Math.random() * 4;

e = Math.random() * 4;

c = Math.random() * 4;

d = Math.random() * 4;

i = 0;

flage = 0;

flagg = 0;

dejong = function(x, y) {
  var x2, y2;
  x2 = Math.sin(a * y) + (c * Math.cos(a * x));
  y2 = Math.sin(e * x) + (d * Math.cos(e * y));
  return [x2, y2];
};

width = 750;

height = 750;

canvas = d3.select('body').append('canvas').attr('width', width).attr('height', height);

context = canvas.node().getContext('2d');

context.translate(width / 2, height / 2);

context.scale(60, 60);

document.addEventListener('click', function() {
  return console.log("a " + a + " e " + e + " c " + c + " d " + d);
});

setInterval(function() {
  var b, r, ref;
  context.globalCompositeOperation = 'source-over';
  context.fillStyle = "rgba(0,0,0,0.2)";
  context.fillRect(-500, -500, 1000, 1000);
  context.globalCompositeOperation = 'lighter';
  while (i < 7000) {
    r = Math.floor(Math.abs(x) * 150);
    b = Math.floor(Math.abs(y) * 150);
    context.fillStyle = "rgba(" + r + ", 40, " + b + ", 1)";
    ref = dejong(x, y), x = ref[0], y = ref[1];
    i++;
    context.fillRect(x, y, 0.01, 0.01);
    context.stroke();
    context.restore();
  }
  i = 0;
  if (flage === 0) {
    e += Math.random() / 100;
  } else {
    e -= Math.random() / 100;
  }
  if (flagg === 0) {
    d -= Math.random() / 100;
  } else {
    d += Math.random() / 100;
  }
  if (e > 4) {
    a = a + (Math.random() / 100);
    flage = 1;
  } else if (e < -4) {
    a = a - (Math.random() / 100);
    flage = 0;
  }
  if (d < -4) {
    c = c + (Math.random() / 100);
    return flagg = 1;
  } else if (d > 4) {
    c = c - (Math.random() / 100);
    return flagg = 0;
  }
}, 7);

// ---
// generated by coffee-script 1.9.2